"""baseline

Revision ID: 012fa0498b24
Revises: 
Create Date: 2026-04-02 00:30:27.198921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '012fa0498b24'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verification_codes_email'), 'email_verification_codes', ['email'], unique=False)
    op.create_table('prompts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service', sa.String(length=50), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('variables', postgresql.JSON(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service', 'key', name='uq_prompts_service_key')
    )
    op.create_index(op.f('ix_prompts_service'), 'prompts', ['service'], unique=False)
    op.create_table('revoked_access_tokens',
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('google_sub', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=True)
    op.create_table('feedback_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_session_id', sa.UUID(), nullable=False),
    sa.Column('source_answer_id', sa.UUID(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('topic', sa.String(length=500), nullable=False),
    sa.Column('mistake', sa.Text(), nullable=False),
    sa.Column('correction', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='see', nullable=False),
    sa.Column('review_question', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_notes_user_session', 'feedback_notes', ['user_id', 'source_session_id'], unique=False)
    op.create_index('ix_feedback_notes_user_source_type', 'feedback_notes', ['user_id', 'source_type'], unique=False)
    op.create_table('folders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('user', 'a_level', 'gcse', name='foldertype', native_enum=False, length=20), server_default='user', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_folders_user_id'), 'folders', ['user_id'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('num_blocks', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_user_id'), 'lessons', ['user_id'], unique=False)
    op.create_table('llm_usage_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('feature', sa.String(length=64), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_usage_log_feature'), 'llm_usage_log', ['feature'], unique=False)
    op.create_index(op.f('ix_llm_usage_log_user_id'), 'llm_usage_log', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('prompt_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prompt_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('changed_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_versions_prompt_id'), 'prompt_versions', ['prompt_id'], unique=False)
    op.create_table('referral_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_sources_code'), 'referral_sources', ['code'], unique=True)
    op.create_index(op.f('ix_referral_sources_user_id'), 'referral_sources', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('access_jti', sa.String(length=36), nullable=True),
    sa.Column('access_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_access_jti'), 'refresh_tokens', ['access_jti'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('folder_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_folder_id'), 'conversations', ['folder_id'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('folder_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('source_s3_key', sa.String(length=1000), nullable=False),
    sa.Column('processed_s3_key', sa.String(length=1000), nullable=True),
    sa.Column('markdown_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_s3_key')
    )
    op.create_index(op.f('ix_documents_folder_id'), 'documents', ['folder_id'], unique=False)
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_table('exams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('folder_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('exam_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('roadmap_nodes', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exams_folder_id'), 'exams', ['folder_id'], unique=False)
    op.create_index(op.f('ix_exams_user_id'), 'exams', ['user_id'], unique=False)
    op.create_table('feynman_blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('scope', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('points', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feynman_blocks_lesson_id'), 'feynman_blocks', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_feynman_blocks_user_id'), 'feynman_blocks', ['user_id'], unique=False)
    op.create_table('lesson_blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('is_summary', sa.Boolean(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_blocks_block_id'), 'lesson_blocks', ['block_id'], unique=False)
    op.create_index(op.f('ix_lesson_blocks_lesson_id'), 'lesson_blocks', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_lesson_blocks_user_id'), 'lesson_blocks', ['user_id'], unique=False)
    op.create_table('lesson_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stars', sa.SmallInteger(), nullable=False),
    sa.Column('study_star', sa.Boolean(), nullable=False),
    sa.Column('feynman_star', sa.Boolean(), nullable=False),
    sa.Column('test_star', sa.Boolean(), nullable=False),
    sa.Column('mastery', sa.Float(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'user_id', name='uq_lesson_progress_lesson_user')
    )
    op.create_index(op.f('ix_lesson_progress_lesson_id'), 'lesson_progress', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_lesson_progress_user_id'), 'lesson_progress', ['user_id'], unique=False)
    op.create_table('megaclusters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('folder_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('document_ids', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('cluster_uuids', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_megaclusters_folder_id'), 'megaclusters', ['folder_id'], unique=False)
    op.create_table('referral_attributions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('visitor_id', sa.String(length=36), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['referral_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_referral_attributions_user_id')
    )
    op.create_index(op.f('ix_referral_attributions_source_id'), 'referral_attributions', ['source_id'], unique=False)
    op.create_table('referral_visits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('visitor_id', sa.String(length=36), nullable=False),
    sa.Column('landing_page', sa.String(length=2048), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('visited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['referral_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_visits_source_id'), 'referral_visits', ['source_id'], unique=False)
    op.create_index(op.f('ix_referral_visits_visitor_id'), 'referral_visits', ['visitor_id'], unique=False)
    op.create_table('roadmap_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('folder_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['roadmap_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_nodes_folder_id'), 'roadmap_nodes', ['folder_id'], unique=False)
    op.create_index(op.f('ix_roadmap_nodes_lesson_id'), 'roadmap_nodes', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_roadmap_nodes_parent_id'), 'roadmap_nodes', ['parent_id'], unique=False)
    op.create_table('test_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('folder_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('node_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('total_marks', sa.Integer(), nullable=True),
    sa.Column('mark_scheme', sa.Text(), nullable=True),
    sa.Column('original_filename', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_templates_folder_id'), 'test_templates', ['folder_id'], unique=False)
    op.create_index(op.f('ix_test_templates_lesson_id'), 'test_templates', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_test_templates_user_id'), 'test_templates', ['user_id'], unique=False)
    op.create_table('user_folder_positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('folder_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'folder_id', name='uq_user_folder_position')
    )
    op.create_index(op.f('ix_user_folder_positions_user_id'), 'user_folder_positions', ['user_id'], unique=False)
    op.create_table('evidence_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False, comment='Stable hash per question/feynman point for repeat detection'),
    sa.Column('source_type', sa.String(length=30), nullable=False, comment='inline_mcq | inline_short | mini_feynman | feynman | lesson_test | standalone_test | past_paper | verify_card'),
    sa.Column('source_id', sa.UUID(), nullable=False, comment='lesson_id, test_template_id, or feedback_note_id'),
    sa.Column('attempt_id', sa.UUID(), nullable=False, comment='TestSession.id or FeynmanSession.id — groups events per attempt'),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False, comment='s ∈ [0, 1]: 1.0=fully correct, 0.0=fully wrong'),
    sa.Column('quality_weight', sa.Float(), nullable=False, comment='q: evidence strength from source type (0.5–1.5)'),
    sa.Column('repeat_discount', sa.Float(), nullable=False, comment='d: 1.0 for first attempt, <1.0 for repeats'),
    sa.Column('invalidated', sa.Boolean(), nullable=False, comment='True when superseded by a newer attempt of the same source'),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['roadmap_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_attempt', 'evidence_events', ['attempt_id'], unique=False)
    op.create_index('ix_evidence_source', 'evidence_events', ['user_id', 'node_id', 'source_type', 'invalidated'], unique=False)
    op.create_index('ix_evidence_user_item', 'evidence_events', ['user_id', 'item_id'], unique=False)
    op.create_index('ix_evidence_user_node', 'evidence_events', ['user_id', 'node_id'], unique=False)
    op.create_table('feynman_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feynman_block_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('current_iteration', sa.Integer(), nullable=False),
    sa.Column('covered_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('feedback', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feynman_block_id'], ['feynman_blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feynman_sessions_feynman_block_id'), 'feynman_sessions', ['feynman_block_id'], unique=False)
    op.create_index(op.f('ix_feynman_sessions_user_id'), 'feynman_sessions', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant', 'tool_call', 'tool_result')", name='ck_messages_role'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('folder_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'processing', 'splitting', 'clustering', 'embedding', 'completed', 'failed', name='processing_job_status'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('source_s3_key', sa.String(length=1000), nullable=False),
    sa.Column('processed_s3_key', sa.String(length=1000), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_jobs_document_id'), 'processing_jobs', ['document_id'], unique=True)
    op.create_index(op.f('ix_processing_jobs_folder_id'), 'processing_jobs', ['folder_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_status'), 'processing_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_processing_jobs_user_id'), 'processing_jobs', ['user_id'], unique=False)
    op.create_table('roadmap_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('progress', sa.SmallInteger(), nullable=False),
    sa.Column('mastery', sa.Float(), nullable=True),
    sa.Column('stars', sa.SmallInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['roadmap_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', 'user_id', name='uq_roadmap_progress_node_user')
    )
    op.create_index(op.f('ix_roadmap_progress_user_id'), 'roadmap_progress', ['user_id'], unique=False)
    op.create_index('ix_roadmap_progress_user_node', 'roadmap_progress', ['user_id', 'node_id'], unique=False)
    op.create_table('test_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('correct_option_index', sa.Integer(), nullable=True),
    sa.Column('model_answer', sa.Text(), nullable=True),
    sa.Column('mark_scheme', sa.Text(), nullable=True),
    sa.Column('hint', sa.Text(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('sources', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('node_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('item_id', sa.String(length=32), nullable=True),
    sa.Column('inline_key', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['test_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_questions_inline_key'), 'test_questions', ['inline_key'], unique=False)
    op.create_index(op.f('ix_test_questions_template_id'), 'test_questions', ['template_id'], unique=False)
    op.create_table('test_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('earned_marks', sa.Integer(), nullable=True),
    sa.Column('total_marks', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['test_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_sessions_template_id'), 'test_sessions', ['template_id'], unique=False)
    op.create_index(op.f('ix_test_sessions_user_id'), 'test_sessions', ['user_id'], unique=False)
    op.create_table('feynman_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['feynman_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feynman_messages_session_id'), 'feynman_messages', ['session_id'], unique=False)
    op.create_table('session_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('earned_marks', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['test_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['test_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'question_id', name='uq_session_answer_session_question')
    )
    op.create_index(op.f('ix_session_answers_question_id'), 'session_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_session_answers_session_id'), 'session_answers', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_answers_session_id'), table_name='session_answers')
    op.drop_index(op.f('ix_session_answers_question_id'), table_name='session_answers')
    op.drop_table('session_answers')
    op.drop_index(op.f('ix_feynman_messages_session_id'), table_name='feynman_messages')
    op.drop_table('feynman_messages')
    op.drop_index(op.f('ix_test_sessions_user_id'), table_name='test_sessions')
    op.drop_index(op.f('ix_test_sessions_template_id'), table_name='test_sessions')
    op.drop_table('test_sessions')
    op.drop_index(op.f('ix_test_questions_template_id'), table_name='test_questions')
    op.drop_index(op.f('ix_test_questions_inline_key'), table_name='test_questions')
    op.drop_table('test_questions')
    op.drop_index('ix_roadmap_progress_user_node', table_name='roadmap_progress')
    op.drop_index(op.f('ix_roadmap_progress_user_id'), table_name='roadmap_progress')
    op.drop_table('roadmap_progress')
    op.drop_index(op.f('ix_processing_jobs_user_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_status'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_folder_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_document_id'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_feynman_sessions_user_id'), table_name='feynman_sessions')
    op.drop_index(op.f('ix_feynman_sessions_feynman_block_id'), table_name='feynman_sessions')
    op.drop_table('feynman_sessions')
    op.drop_index('ix_evidence_user_node', table_name='evidence_events')
    op.drop_index('ix_evidence_user_item', table_name='evidence_events')
    op.drop_index('ix_evidence_source', table_name='evidence_events')
    op.drop_index('ix_evidence_attempt', table_name='evidence_events')
    op.drop_table('evidence_events')
    op.drop_index(op.f('ix_user_folder_positions_user_id'), table_name='user_folder_positions')
    op.drop_table('user_folder_positions')
    op.drop_index(op.f('ix_test_templates_user_id'), table_name='test_templates')
    op.drop_index(op.f('ix_test_templates_lesson_id'), table_name='test_templates')
    op.drop_index(op.f('ix_test_templates_folder_id'), table_name='test_templates')
    op.drop_table('test_templates')
    op.drop_index(op.f('ix_roadmap_nodes_parent_id'), table_name='roadmap_nodes')
    op.drop_index(op.f('ix_roadmap_nodes_lesson_id'), table_name='roadmap_nodes')
    op.drop_index(op.f('ix_roadmap_nodes_folder_id'), table_name='roadmap_nodes')
    op.drop_table('roadmap_nodes')
    op.drop_index(op.f('ix_referral_visits_visitor_id'), table_name='referral_visits')
    op.drop_index(op.f('ix_referral_visits_source_id'), table_name='referral_visits')
    op.drop_table('referral_visits')
    op.drop_index(op.f('ix_referral_attributions_source_id'), table_name='referral_attributions')
    op.drop_table('referral_attributions')
    op.drop_index(op.f('ix_megaclusters_folder_id'), table_name='megaclusters')
    op.drop_table('megaclusters')
    op.drop_index(op.f('ix_lesson_progress_user_id'), table_name='lesson_progress')
    op.drop_index(op.f('ix_lesson_progress_lesson_id'), table_name='lesson_progress')
    op.drop_table('lesson_progress')
    op.drop_index(op.f('ix_lesson_blocks_user_id'), table_name='lesson_blocks')
    op.drop_index(op.f('ix_lesson_blocks_lesson_id'), table_name='lesson_blocks')
    op.drop_index(op.f('ix_lesson_blocks_block_id'), table_name='lesson_blocks')
    op.drop_table('lesson_blocks')
    op.drop_index(op.f('ix_feynman_blocks_user_id'), table_name='feynman_blocks')
    op.drop_index(op.f('ix_feynman_blocks_lesson_id'), table_name='feynman_blocks')
    op.drop_table('feynman_blocks')
    op.drop_index(op.f('ix_exams_user_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_folder_id'), table_name='exams')
    op.drop_table('exams')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_folder_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_folder_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_access_jti'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_referral_sources_user_id'), table_name='referral_sources')
    op.drop_index(op.f('ix_referral_sources_code'), table_name='referral_sources')
    op.drop_table('referral_sources')
    op.drop_index(op.f('ix_prompt_versions_prompt_id'), table_name='prompt_versions')
    op.drop_table('prompt_versions')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_llm_usage_log_user_id'), table_name='llm_usage_log')
    op.drop_index(op.f('ix_llm_usage_log_feature'), table_name='llm_usage_log')
    op.drop_table('llm_usage_log')
    op.drop_index(op.f('ix_lessons_user_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_folders_user_id'), table_name='folders')
    op.drop_table('folders')
    op.drop_index('ix_feedback_notes_user_source_type', table_name='feedback_notes')
    op.drop_index('ix_feedback_notes_user_session', table_name='feedback_notes')
    op.drop_table('feedback_notes')
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('revoked_access_tokens')
    op.drop_index(op.f('ix_prompts_service'), table_name='prompts')
    op.drop_table('prompts')
    op.drop_index(op.f('ix_email_verification_codes_email'), table_name='email_verification_codes')
    op.drop_table('email_verification_codes')
    # ### end Alembic commands ###
