"""add mark_scheme_filename to test_templates

Revision ID: 221c2876b837
Revises: 17f2e904b1c3
Create Date: 2026-04-03 20:21:47.480934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '221c2876b837'
down_revision: Union[str, None] = '17f2e904b1c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_templates', sa.Column('mark_scheme_filename', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_templates', 'mark_scheme_filename')
    # ### end Alembic commands ###
