"""add ocr_markdown to test_templates

Revision ID: 3041cec3a8b5
Revises: 221c2876b837
Create Date: 2026-04-03 23:12:31.692956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3041cec3a8b5'
down_revision: Union[str, None] = '221c2876b837'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_templates', sa.Column('ocr_markdown', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_templates', 'ocr_markdown')
    # ### end Alembic commands ###
