"""add_mark_scheme_sha256_to_test_templates

Revision ID: 38e3a698a91f
Revises: ff8ea39e7d6f
Create Date: 2026-04-13 01:46:21.764486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38e3a698a91f'
down_revision: Union[str, None] = 'ff8ea39e7d6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_templates', sa.Column('mark_scheme_sha256', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_test_templates_mark_scheme_sha256'), 'test_templates', ['mark_scheme_sha256'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_templates_mark_scheme_sha256'), table_name='test_templates')
    op.drop_column('test_templates', 'mark_scheme_sha256')
    # ### end Alembic commands ###
