"""add_citations_to_feynman_messages

Revision ID: 43fc5e9ac344
Revises: c4a95d4906e1
Create Date: 2026-04-20 23:29:08.757643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43fc5e9ac344'
down_revision: Union[str, None] = 'c4a95d4906e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feynman_messages', sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feynman_messages', 'citations')
    # ### end Alembic commands ###
