"""add is_self_reported to session_answers

Revision ID: 6b781d2bf3bc
Revises: 7e68eb748de4
Create Date: 2026-04-24 18:00:15.519322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b781d2bf3bc'
down_revision: Union[str, None] = '7e68eb748de4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_answers', sa.Column('is_self_reported', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_answers', 'is_self_reported')
    # ### end Alembic commands ###
