"""defer_referral_attribution_until_verification

Revision ID: 7c8b0a8190b1
Revises: 8aef54f52466
Create Date: 2026-05-03 19:39:51.809363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c8b0a8190b1'
down_revision: Union[str, None] = '8aef54f52466'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pending_ref_code', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('pending_visitor_id', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pending_visitor_id')
    op.drop_column('users', 'pending_ref_code')
    # ### end Alembic commands ###
