"""add is_unsupported to test_questions

Revision ID: 7e68eb748de4
Revises: 826540e972eb
Create Date: 2026-04-24 16:13:59.288049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e68eb748de4'
down_revision: Union[str, None] = '826540e972eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_questions', sa.Column('is_unsupported', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_questions', 'is_unsupported')
    # ### end Alembic commands ###
