"""add question_number to test_questions

Revision ID: 826540e972eb
Revises: 8a0c1f2e3b4dg
Create Date: 2026-04-24 00:42:03.588972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '826540e972eb'
down_revision: Union[str, None] = '8a0c1f2e3b4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_questions', sa.Column('question_number', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_questions', 'question_number')
    # ### end Alembic commands ###
