"""add_admin_ip_blacklist

Revision ID: 8538506a0e81
Revises: deb7186c2ce2
Create Date: 2026-04-17 13:30:35.373369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8538506a0e81'
down_revision: Union[str, None] = 'deb7186c2ce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_ip_blacklist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('blocked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_ip_blacklist_ip'), 'admin_ip_blacklist', ['ip'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_ip_blacklist_ip'), table_name='admin_ip_blacklist')
    op.drop_table('admin_ip_blacklist')
    # ### end Alembic commands ###
