"""add_pending_columns_and_processing_phase

Revision ID: a7c4ff3c44a3
Revises: f083c1a5a9a5
Create Date: 2026-04-07 02:01:19.452028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7c4ff3c44a3'
down_revision: Union[str, None] = 'f083c1a5a9a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('scope_type', sa.String(length=20), nullable=True))
    op.add_column('conversations', sa.Column('feedback_note_id', sa.UUID(), nullable=True))
    op.add_column('conversations', sa.Column('active_path', postgresql.ARRAY(sa.UUID()), nullable=True))
    op.create_index(op.f('ix_conversations_feedback_note_id'), 'conversations', ['feedback_note_id'], unique=False)
    op.create_index(op.f('ix_conversations_scope_type'), 'conversations', ['scope_type'], unique=False)
    op.create_foreign_key(None, 'conversations', 'feedback_notes', ['feedback_note_id'], ['id'], ondelete='SET NULL')
    op.add_column('messages', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.add_column('messages', sa.Column('version_index', sa.Integer(), server_default='1', nullable=False))
    op.create_index('ix_messages_conv_parent', 'messages', ['conversation_id', 'parent_id'], unique=False)
    op.create_index('ix_messages_conv_parent_role', 'messages', ['conversation_id', 'parent_id', 'role'], unique=False)
    op.create_index(op.f('ix_messages_parent_id'), 'messages', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'messages', ['parent_id'], ['id'], ondelete='SET NULL')
    op.add_column('test_templates', sa.Column('generation_progress', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True))
    op.add_column('test_templates', sa.Column('generation_task_id', sa.String(length=100), nullable=True))
    op.add_column('test_templates', sa.Column('question_type_counts', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_templates', 'question_type_counts')
    op.drop_column('test_templates', 'generation_task_id')
    op.drop_column('test_templates', 'generation_progress')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_parent_id'), table_name='messages')
    op.drop_index('ix_messages_conv_parent_role', table_name='messages')
    op.drop_index('ix_messages_conv_parent', table_name='messages')
    op.drop_column('messages', 'version_index')
    op.drop_column('messages', 'parent_id')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_scope_type'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_feedback_note_id'), table_name='conversations')
    op.drop_column('conversations', 'active_path')
    op.drop_column('conversations', 'feedback_note_id')
    op.drop_column('conversations', 'scope_type')
    # ### end Alembic commands ###
