"""add folder_id to lessons and feedback_notes

Revision ID: bd35b64317a2
Revises: 43fc5e9ac344
Create Date: 2026-04-21 06:21:28.684336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd35b64317a2'
down_revision: Union[str, None] = '43fc5e9ac344'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback_notes', sa.Column('folder_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_feedback_notes_folder_id'), 'feedback_notes', ['folder_id'], unique=False)
    op.create_foreign_key('fk_feedback_notes_folder_id', 'feedback_notes', 'folders', ['folder_id'], ['id'], ondelete='SET NULL')
    op.add_column('lessons', sa.Column('folder_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_lessons_folder_id'), 'lessons', ['folder_id'], unique=False)
    op.create_foreign_key('fk_lessons_folder_id', 'lessons', 'folders', ['folder_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_lessons_folder_id', 'lessons', type_='foreignkey')
    op.drop_index(op.f('ix_lessons_folder_id'), table_name='lessons')
    op.drop_column('lessons', 'folder_id')
    op.drop_constraint('fk_feedback_notes_folder_id', 'feedback_notes', type_='foreignkey')
    op.drop_index(op.f('ix_feedback_notes_folder_id'), table_name='feedback_notes')
    op.drop_column('feedback_notes', 'folder_id')
    # ### end Alembic commands ###
