"""add_folder_pqg_service

Revision ID: c4a95d4906e1
Revises: 662380af7606
Create Date: 2026-04-17 14:41:25.029259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4a95d4906e1'
down_revision: Union[str, None] = '662380af7606'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folders', sa.Column('pqg_service', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('folders', 'pqg_service')
    # ### end Alembic commands ###
