"""replace is_self_reported with image_key on session_answers

Revision ID: c6e27125ce6d
Revises: 6b781d2bf3bc
Create Date: 2026-04-25 20:27:32.873102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6e27125ce6d'
down_revision: Union[str, None] = '6b781d2bf3bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_answers', sa.Column('image_key', sa.String(length=500), nullable=True))
    op.drop_column('session_answers', 'is_self_reported')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_answers', sa.Column('is_self_reported', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('session_answers', 'image_key')
    # ### end Alembic commands ###
