"""add lesson_highlights table

Revision ID: f083c1a5a9a5
Revises: ecdd360ff44b
Create Date: 2026-04-05 10:17:13.296881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f083c1a5a9a5'
down_revision: Union[str, None] = 'ecdd360ff44b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_highlights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_highlights_lesson_id'), 'lesson_highlights', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_lesson_highlights_user_id'), 'lesson_highlights', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lesson_highlights_user_id'), table_name='lesson_highlights')
    op.drop_index(op.f('ix_lesson_highlights_lesson_id'), table_name='lesson_highlights')
    op.drop_table('lesson_highlights')
    # ### end Alembic commands ###
