"""add_source_pdf_sha256_to_test_templates

Revision ID: ff8ea39e7d6f
Revises: 67d2a0ff8732
Create Date: 2026-04-13 00:57:02.525496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff8ea39e7d6f'
down_revision: Union[str, None] = '67d2a0ff8732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_templates', sa.Column('source_pdf_sha256', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_test_templates_source_pdf_sha256'), 'test_templates', ['source_pdf_sha256'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_templates_source_pdf_sha256'), table_name='test_templates')
    op.drop_column('test_templates', 'source_pdf_sha256')
    # ### end Alembic commands ###
